version: "3.8"

services:
  site:
    build:
      context: .
      dockerfile: docker/Dockerfile.docs
    image: docker.io/library/jekyll:latest
    tty: true
    working_dir: /docs
    volumes:
      - ./docs:/docs
    ports: 
      - "4000:4000"
    # network_mode: 'host'
    command: >
      sh -c "bundle exec jekyll serve --host 0.0.0.0"

